[v1]
"alacritty 0.13.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["alacritty"]
"bacon 2.18.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["bacon"]
"bandwhich 0.22.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["bandwhich"]
"bat 0.24.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"bunyan 0.1.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["bunyan"]
"cargo-audit 0.20.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-audit"]
"cargo-expand 1.0.88 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-nextest 0.9.78 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-nextest"]
"cargo-tarpaulin 0.30.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-tarpaulin"]
"cargo-udeps 0.1.49 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-udeps"]
"cargo-watch 8.5.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch"]
"eza 0.18.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["eza"]
"git-delta 0.16.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["delta"]
"hurl 4.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hurl"]
"hyperfine 1.15.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine"]
"just 1.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["just"]
"neovide 0.15.2 (git+https://github.com/neovide/neovide#0df980b6d4e5887f49925f2b7419b7b0dc5c0b8d)" = ["neovide"]
"nu 0.90.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["nu"]
"ripgrep 14.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"sniffnet 1.2.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["sniffnet"]
"speedtest-rs 0.1.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["speedtest-rs"]
"sqlx-cli 0.7.4 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-sqlx",
    "sqlx",
]
"trunk 0.16.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["trunk"]
"wasm-bindgen-cli 0.2.84 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "wasm-bindgen",
    "wasm-bindgen-test-runner",
    "wasm2es6js",
]
"workshop-runner 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["wr"]
"zellij 0.39.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["zellij"]
"zoxide 0.9.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide"]
